# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7135494573a106c054b784c0e6c568901e7262482934e486f3a08f449f15e12c4dac5a23925b496b9728fc2d446921559aea30318101e77c9cdbc241976d2f8b

test:
  secret_key_base: db669a8f91f92830506b3a451fdba92da875a47c46698af7348422b19cdd0734354dc3045872a21fe1ba102b41c1531542e42ff64f55e3695ed208650db6ef30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
